In [192]:
import pandas as pd
import numpy as np
# from Mediapipe.luxvis import*
import cv2
import glob
from sklearn.datasets import make_blobs
import matplotlib.pyplot as pl

In [193]:
path= ('/home/roopesh/Desktop/Result of Mask/*png')
def file_path(path):
    for idx,file in enumerate(glob.glob(path)):
        images = cv2.imread(file)

    # conversion numpy array into rgb image to show

        image_bgr_rgb = cv2.cvtColor(images, cv2.COLOR_BGR2RGB)
        image_rgb_bgr = cv2.cvtColor(image_bgr_rgb, cv2.COLOR_RGB2BGR)
        resized = image_rgb_bgr
    # resize 3d to 2d numpy array

    # Dimensions: [m, n, 3]
        resized = resized.transpose()
        # Dimensions: [3, m, n]
        resized = resized.reshape( (resized.shape[1]*resized.shape[2]),resized.shape[0]) # re shaping by multiplying (height*width), channel to make 2d
#         print('2-dim array', resized[:5])
#         print('Resized Result Mask Shape', resized.shape)
#         print('Resized Result Mask Data type: ',resized.dtype)
        resized =pd.DataFrame(resized)
        resized1= resized.copy()
        resized1.replace({255: np.nan}, inplace = True)
        resized1.dropna(inplace=True)
        resized1.astype('int')
        resized1.to_csv(f'/home/roopesh/Desktop/CSV/{idx}.csv', sep=',',index=False,header=False)
        return resized1

if __name__ == '__main__':
    pa= ('/home/roopesh/Desktop/Result of Mask/*png')
    file_path(pa)

In [194]:
new =image_rgb_bgr 

In [195]:
new1= new.transpose(2,0,1).reshape(3,-1)

In [196]:
new1.shape

(3, 307200)

In [197]:

resized = image_rgb_bgr
# resize 3d to 2d numpy array

# Dimensions: [m, n, 3]
resized = resized.transpose()
# Dimensions: [3, m, n]
resized = resized.reshape( (resized.shape[1]*resized.shape[2]),resized.shape[0]) # re shaping by multiplying (height*width), channel to make 2d
print('2-dim array', resized[:5])
print('Resized Result Mask Shape', resized.shape)
print('Resized Result Mask Data type: ',resized.dtype)





2-dim array [[255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]
 [255 255 255]]
Resized Result Mask Shape (307200, 3)
Resized Result Mask Data type:  uint8


In [198]:

resized =pd.DataFrame(resized)

In [199]:
resized1= resized.copy()

In [200]:
resized1.shape

(307200, 3)

In [201]:
resized1=pd.DataFrame(resized1)

In [202]:
r, c = resized1.shape

In [203]:
resized1.head()

0    1    2
0  255  255  255
1  255  255  255
2  255  255  255
3  255  255  255
4  255  255  255

In [204]:
print(r)

307200


In [205]:
print(c)

3


In [206]:
resized1.describe()

0              1              2
count  307200.000000  307200.000000  307200.000000
mean      254.874479     254.872663     254.871331
std         5.293438       5.284895       5.334211
min         0.000000       0.000000       0.000000
25%       255.000000     255.000000     255.000000
50%       255.000000     255.000000     255.000000
75%       255.000000     255.000000     255.000000
max       255.000000     255.000000     255.000000

In [207]:
resized1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307200 entries, 0 to 307199
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       307200 non-null  uint8
 1   1       307200 non-null  uint8
 2   2       307200 non-null  uint8
dtypes: uint8(3)
memory usage: 900.1 KB


In [224]:
resized1.replace({255: np.nan}, inplace = True)

In [213]:
resized1.nunique()

0    43
1    57
2    49
dtype: int64

In [225]:

resized1.dropna(inplace=True)

In [239]:
resized1=resized1.astype('int')

In [241]:
resized1.to_csv(f'/home/roopesh/Desktop/CSV/{idx}.csv', sep=',',index=False,header=False)

In [231]:
resized1.shape

(126, 3)

In [160]:

dic1 = []
for y in resized1[1]:
    if (y!=255): 
        print('channel 1',y)
        dic1.append(y)


channel 1 44
channel 1 40
channel 1 62
channel 1 33
channel 1 42
channel 1 51
channel 1 25
channel 1 45
channel 1 31
channel 1 35
channel 1 74
channel 1 30
channel 1 35
channel 1 25
channel 1 45
channel 1 35
channel 1 40
channel 1 38
channel 1 35
channel 1 30
channel 1 34
channel 1 40
channel 1 26
channel 1 31
channel 1 41
channel 1 38
channel 1 32
channel 1 41
channel 1 37
channel 1 37
channel 1 45
channel 1 39
channel 1 37
channel 1 36
channel 1 38
channel 1 51
channel 1 39
channel 1 41
channel 1 40
channel 1 45
channel 1 45
channel 1 39
channel 1 46
channel 1 49
channel 1 48
channel 1 50
channel 1 75
channel 1 46
channel 1 46
channel 1 80
channel 1 38
channel 1 33
channel 1 56
channel 1 29
channel 1 39
channel 1 46
channel 1 23
channel 1 0
channel 1 38
channel 1 36
channel 1 0
channel 1 29
channel 1 81
channel 1 0
channel 1 24
channel 1 30
channel 1 22
channel 1 38
channel 1 29
channel 1 40
channel 1 30
channel 1 29
channel 1 24
channel 1 28
channel 1 34
channel 1 23
channel 1 24
ch

In [163]:
dic2=[]
for z in resized1[2]:
    if (z!=255): 
        print('channel 2',z)
        dic2.append(z)

channel 2 25
channel 2 41
channel 2 68
channel 2 33
channel 2 36
channel 2 55
channel 2 34
channel 2 36
channel 2 39
channel 2 25
channel 2 31
channel 2 37
channel 2 33
channel 2 37
channel 2 33
channel 2 32
channel 2 35
channel 2 28
channel 2 37
channel 2 43
channel 2 33
channel 2 36
channel 2 28
channel 2 32
channel 2 31
channel 2 33
channel 2 38
channel 2 44
channel 2 32
channel 2 34
channel 2 37
channel 2 40
channel 2 34
channel 2 39
channel 2 40
channel 2 37
channel 2 39
channel 2 36
channel 2 47
channel 2 50
channel 2 45
channel 2 47
channel 2 41
channel 2 50
channel 2 41
channel 2 48
channel 2 53
channel 2 50
channel 2 50
channel 2 60
channel 2 24
channel 2 35
channel 2 62
channel 2 38
channel 2 31
channel 2 49
channel 2 29
channel 2 31
channel 2 34
channel 2 23
channel 2 25
channel 2 31
channel 2 37
channel 2 30
channel 2 0
channel 2 31
channel 2 26
channel 2 0
channel 2 31
channel 2 23
channel 2 0
channel 2 31
channel 2 44
channel 2 26
channel 2 30
channel 2 22
channel 2 26
ch

In [169]:
list1=[dic]
list2=[dic1]
list3 = [dic]
dictionary = [{'channel0':dic}, {'channel1':dic1},{'channel2':dic2}]

In [170]:
dictionary

[{'channel0': [36,
   49,
   23,
   36,
   56,
   32,
   36,
   43,
   33,
   36,
   25,
   33,
   35,
   35,
   34,
   32,
   38,
   37,
   27,
   34,
   39,
   31,
   36,
   35,
   43,
   36,
   36,
   37,
   35,
   35,
   37,
   42,
   39,
   40,
   43,
   41,
   37,
   45,
   46,
   47,
   58,
   43,
   47,
   59,
   49,
   60,
   30,
   44,
   23,
   31,
   50,
   37,
   30,
   38,
   28,
   0,
   31,
   23,
   27,
   29,
   37,
   0,
   28,
   25,
   32,
   31,
   23,
   27,
   32,
   24,
   30,
   29,
   37,
   31,
   31,
   34,
   33,
   29,
   35,
   37,
   0,
   36,
   36,
   39,
   38,
   36,
   0,
   44,
   41,
   46,
   57,
   39,
   44,
   56,
   43,
   58,
   0,
   0,
   0,
   46,
   58,
   0,
   42,
   44,
   66,
   66,
   42,
   53,
   0,
   0,
   41,
   0,
   52,
   0,
   42,
   41,
   50,
   0,
   67,
   0,
   47,
   0,
   0,
   41,
   51,
   55,
   46,
   44,
   55,
   0,
   40,
   51,
   0,
   0,
   0,
   0,
   0,
   0,
   44,
   55,
   0,
   45,
   45,
   53,
   5

In [171]:
for key, value in enumerate(dictionary):
    print(key,value)

0 {'channel0': [36, 49, 23, 36, 56, 32, 36, 43, 33, 36, 25, 33, 35, 35, 34, 32, 38, 37, 27, 34, 39, 31, 36, 35, 43, 36, 36, 37, 35, 35, 37, 42, 39, 40, 43, 41, 37, 45, 46, 47, 58, 43, 47, 59, 49, 60, 30, 44, 23, 31, 50, 37, 30, 38, 28, 0, 31, 23, 27, 29, 37, 0, 28, 25, 32, 31, 23, 27, 32, 24, 30, 29, 37, 31, 31, 34, 33, 29, 35, 37, 0, 36, 36, 39, 38, 36, 0, 44, 41, 46, 57, 39, 44, 56, 43, 58, 0, 0, 0, 46, 58, 0, 42, 44, 66, 66, 42, 53, 0, 0, 41, 0, 52, 0, 42, 41, 50, 0, 67, 0, 47, 0, 0, 41, 51, 55, 46, 44, 55, 0, 40, 51, 0, 0, 0, 0, 0, 0, 44, 55, 0, 45, 45, 53, 51, 41, 52, 0, 0, 46, 0, 58, 0, 47, 50, 55, 0, 52, 0, 59, 0, 0, 51, 58, 75, 54, 56, 71, 0, 55, 72, 0, 0, 0]}
1 {'channel1': [44, 40, 62, 33, 42, 51, 25, 45, 31, 35, 74, 30, 35, 25, 45, 35, 40, 38, 35, 30, 34, 40, 26, 31, 41, 38, 32, 41, 37, 37, 45, 39, 37, 36, 38, 51, 39, 41, 40, 45, 45, 39, 46, 49, 48, 50, 75, 46, 46, 80, 38, 33, 56, 29, 39, 46, 23, 0, 38, 36, 0, 29, 81, 0, 24, 30, 22, 38, 29, 40, 30, 29, 24, 28, 34, 23, 24, 35

In [ ]:
    a= [if (resized[0]!==255)]:
        print(a)
    b= [if (resized[1]!==255)]:
        print(b)
    c= [if (resized[2]!==255)]:
        print(c)
            

In [139]:
for x in resized1[0]:  
    for y in resized1[1]:
        for z in resized1[2]:
            if (x,y,z!=255): 
                print('channel 0',x,y,z)

KeyboardInterrupt: 

In [155]:
col1 = resized1[0]
print(col1)

0         255
1         255
2         255
3         255
4         255
         ... 
307195    255
307196    255
307197    255
307198    255
307199    255
Name: 0, Length: 307200, dtype: uint8


In [ ]:
row, column= resized1,_

In [106]:
resized1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307200 entries, 0 to 307199
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   0       307200 non-null  uint8
 1   1       307200 non-null  uint8
 2   2       307200 non-null  uint8
dtypes: uint8(3)
memory usage: 900.1 KB


In [112]:
print(column)

2


In [103]:
resized1.head()

0    1    2
0  255  255  255
1  255  255  255
2  255  255  255
3  255  255  255
4  255  255  255

In [105]:
for x in row:
    print(x)

TypeError: 'int' object is not iterable

In [56]:
a=resized1.iloc[255]

In [57]:
a

0    255
1    255
2    255
Name: 255, dtype: uint8

In [25]:
resized = np.delete(resized, np.argwhere(resized == 255))

In [8]:
image_path.resized

AttributeError: 'function' object has no attribute 'resized'